.TH beret 6 "2022-02-19"

.SH NAME
beret \- A 2D puzzle-platformer game about a scientist with telekinetic abilities.

.SH SYNOPSIS
.B beret

.SH DESCRIPTION
.B beret
is a 2D puzzle-platformer game about a scientist, astonishingly named Beret,
who has gained telekinetic abilities through his research at the Evil Corporation.
He decides that the Evil Corporation is a tad too evil for his liking, and begins
his solitary quest to overthrow the corporation and punish the evil deeds of his
employers.
.B beret
has 21 puzzle-filled levels, 120 collectable Medallions, over
20 hours of gameplay, and an unlockable level editor.
.P
.B beret
stores settings and games in
.I ~/.config/beret
.

.SH OPTIONS
There are no known options to beret.

.SH AUTHOR
Beret is copyright 2011 by Nigel Kilmer <kiwisauce@kiwisauce.com>
and is currently maintained by David A. Redick.

Beret is licensed under the terms of the LGPL-3.0

.PP
This manual page was written by David A. Redick,
for the Debian project (and may be used by others).
